services:
  - type: web
    name: documed
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: documed-db
          property: connectionString
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://documed.onrender.com"
      - key: R2_BUCKET_NAME
        value: "documed-media"
      - key: R2_ACCOUNT_ID
        value: "8bbcd32aedca41ce63e50d2c581b7794"
      - key: R2_ENDPOINT_URL
        value: "https://8bbcd32aedca41ce63e50d2c581b7794.r2.cloudflarestorage.com"
      - key: R2_ACCESS_KEY_ID
        sync: false   # set manually in Render dashboard
      - key: R2_SECRET_ACCESS_KEY
        sync: false   # set manually in Render dashboard

databases:
  - name: documed-db
    databaseName: documed
    user: documed
    plan: free
